when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:

when@test: *dev

when@dev: &dev
    zenstruck_foundry:
        # …
        faker:
            locale: fr_FR