controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


api_login_check:
    path: /api/login_check
# config/routes.yaml
# email_test:
#     path: /send-test-email
#     controller: App\Controller\EmailController::sendTestEmail

#? à coder plus tard... 
# token_invalid_page:
#     path: /token-invalid
#     controller: App\Controller\TokenController::invalid

# token_not_found_page:
#     path: /token-not-found
#     controller: App\Controller\TokenController::notFound